/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fred' at '10/25/16 12:09 PM' with Gradle 2.14.1
 *
 * @author fred, @date 10/25/16 12:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
